[package]
name = "sf-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4"
aho-corasick = "1.1.2"
base64 = "0.21.7"
chrono = "0.4.38"
colog = "1.3.0"
fastrand = "2.0.1"
libaes = "0.7.0"
log = "0.4.22"
num-derive = "0.4.2"
num-traits = "0.2.18"
once_cell = "1.19.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.114"
sf-api = "0.1.1"
sha1 = "0.10.6"
sqlx = { version = "0.7", features = ["postgres",  "runtime-tokio-native-tls", "chrono", "macros"] }
strum = { version = "0.26.1", features = ["derive"] }
